name: Quality
on: [push, pull_request]
env:
  REDSCRIPT_VERSION: '0.5.10'
  REDSCRIPT_SRC: scripts/Addicted

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup REDscript
        run: |
          wget https://github.com/jac3km4/redscript/releases/download/v${{ env.REDSCRIPT_VERSION }}/redscript-cli.exe
          chmod +x redscript-cli.exe
      - name: Lint code
        run: ./redscript-cli.exe lint --src ${{ env.REDSCRIPT_SRC }}
        continue-on-error: true
      - name: Compile code
        run: ./redscript-cli.exe compile --src ${{ env.REDSCRIPT_SRC }} --output dump.reds
